# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e5d7b28d91b8278100113d9be7094ae274fe0af4c529f1402963f3947a59fe630c42f5f97503805db8c055e028801f3738c45970a181586ad161d38cdac958

test:
  secret_key_base: 14e7214d9d274d62eee067327f9c6ea2a3ace287bc02c6e5e5d5a4c305dfe44c1076c86cf96bbbf27690794505df9aa0499ad33ab7f834ee655c377bc91a2a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
